apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "actual-assist.fullname" . }}
  labels:
    {{- include "actual-assist.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.nodeEnv | quote }}
  SYNC_INTERVAL_MINUTES: {{ .Values.env.syncIntervalMinutes | quote }}
  SQLITE_DB_PATH: {{ .Values.env.sqliteDbPath | quote }}
  PORT: {{ .Values.env.port | quote }}
  DATA_DIR: {{ .Values.env.dataDir | quote }}
