apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "actual-assist.fullname" . }}-data
  labels:
    {{- include "actual-assist.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
