{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actual-assist.fullname" . }}
  labels:
    {{- include "actual-assist.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.actualServerUrl }}
  ACTUAL_SERVER_URL: {{ .Values.secrets.actualServerUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.actualPassword }}
  ACTUAL_PASSWORD: {{ .Values.secrets.actualPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.actualBudgetId }}
  ACTUAL_BUDGET_ID: {{ .Values.secrets.actualBudgetId | b64enc | quote }}
  {{- end }}
{{- end }}
